# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool: server

steps:
- task: ServiceNow-DevOps-Server-Change-Acceleration@1
  inputs:
    connectedServiceName: 'DevOps ServiceNow connection'
    changeRequestDetails: |
      {
          "setCloseCode" : true,
          "autoCloseChange" : true,
          "attributes": {
            "requested_by": {
              "name": "test user"
            },
            "start_date": "2021-01-05 08:00:00",
            "end_date": "2021-01-08 08:00:00"
          }
        }